### PR TITLE
Add nanotick

### PR DESCRIPTION
**Pull request by yoshuawuyts**
- turn const to var
- use `nanotick`

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
oh lol forgot to patch `nanotick` - there was a bug haha

**Comment by bcomnes** [comment]
What's the purpose behind const -> var?

**Comment by timwis** [comment]
`const` got too popular

**Comment by yoshuawuyts** [comment]
Taste mostly - also been dealing with too much ES6 discussions in the past
year that I'm just gonna drop if all except template strings. Added benefit
is a negligible perf improvement (:

**Comment by bcomnes** [comment]
I've found most benefits of const have been largely outweighed by confusion stemming from variable scope / hoisting differences.  That plus this perf situation might just put this new feature on my revisit in the future list.

**Pull request merged**
