### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by Hypercubed**
Spelling error

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cool, thanks!

**Comment by yoshuawuyts** [comment]
Released as `v6.0.6`

**Comment by Hypercubed** [comment]
Was funny when that poped up.  I didn't know what it meant or which module it was from...  then realized it was my own typo. 😞

**Comment by yoshuawuyts** [comment]
Haha, happens to the best of us teehee :sparkles:

**Pull request merged**
